### ISSUE TITLE
NotFoundError (see above for traceback): Key FaceResNet/conv1/layer_0/Conv/biases not found in checkpoint

### ISSUE THREAD

**Issue by xinliu111** [seasonSH/DocFace#10]
训练后的模型导入报错？？？
NotFoundError (see above for traceback): Key FaceResNet/conv1/layer_0/Conv/biases not found in checkpoint

**Comment by seasonSH** [comment]
Is it an error when restoring my pre-trained model?

**Comment by xinliu111** [comment]
python src/train_sibling.py config/finetune.py
加载预训练模型没有问题，训练完之后的模型导入不了

**Comment by seasonSH** [comment]
Are you trying to continue training your own model that has already been fine-tuned?
If that is the case, try to comment out all the items in the "replace_scopes" in config/finetune.py.

**Comment by huckw** [comment]
I get the same issue whether or not I try continuing from my own model or your base one.  I'm still running an older version which does not have  a "replace_scopes" item in the config (the other difference is I'm still back on the version that wants exactly 2 images per folder named 1.jpg and 2.jpg).  This worked several months ago for me, all I did was generate some new data to train on and now I get the "biases not found in checkpoint"

**Comment by huckw** [comment]
Doh!!!!  Somebody who shares this machine with me had downgraded to Tensorflow 1.1.  I went back to 1.5 and training from your base model works.....trying to start from my pretrained sibling network came up with a "weights not found in checkpoints" issue.

**Comment by hustzeyu** [comment]
> Doh!!!! Somebody who shares this machine with me had downgraded to Tensorflow 1.1. I went back to 1.5 and training from your base model works.....trying to start from my pretrained sibling network came up with a "weights not found in checkpoints" issue.

@huckw   Did you solve the problem?
