### ISSUE TITLE
base model training without se

### ISSUE THREAD

**Issue by hustzeyu** [seasonSH/DocFace#22]
Hi, I am currently training the base model without se-module. The reg_loss decreased from 1.031 to 0.065 while the am loss seems stay at 16.287. Isn't training without Se-module just by commenting out the following part:
                    if i % 2 == 1:
                    net = se_module(net)
                    net = net + shortcut
                    shortcut = net
                    print('| shortcut')
at the face_resnet.py ? Would you please help me? Thank you.

**Comment by hustzeyu** [comment]
I have tried to train the base model with Se-module from the beginning this morning,  which is your original code without your pre-trained model, but still I have got the same result. The reg_loss has reduced dramatically from 1.068 while the (am) loss flatuated around 16.3 
Is it normal? Do you have the same process?

**Comment by kirilles** [comment]
@hustzeyu hi, did you solve the problem? I have exactly the same loss behaviour
