### ISSUE TITLE
How can I mention the imagelist.txt file?

### ISSUE THREAD

**Issue by ytgcljj** [seasonSH/DocFace#4]
How do you use it?

**Comment by ytgcljj** [comment]
Can you give a complete case?

**Comment by seasonSH** [comment]
I have just updated the code. Now the order of the image list does not matter. You just need to make sure that these images follow the same naming convention as in the training dataset. For example, it can be like this:

/***/***/A001.jpg
/***/***/A002.jpg
/***/***/B001.jpg
...

The code will detect the the first chacacter of the file name to decide which type of image it is (ID or selfie).

**Comment by ytgcljj** [comment]
I just downloaded BaseModel and ran Python Src / extract_features. py -- model_dir log / faceres_ms -- image_list image list. TXT -- output. NPY error


launchx@launchx-System-Product-Name:~/DocFace$ python src/extract_features.py --model_dir log/faceres_ms --image_list imagelist.txt --output output.npy
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.7.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.7.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.7.5 locally
Traceback (most recent call last):
  File "src/extract_features.py", line 86, in <module>
    main(args)
  File "src/extract_features.py", line 41, in main
    config = utils.import_file(os.path.join(args.model_dir, 'config.py'), 'config')
  File "/home/launchx/DocFace/src/utils.py", line 46, in import_file
    module_obj = imp.load_source(name, full_path_to_module)
  File "/home/launchx/anaconda2/envs/rllab3/lib/python3.5/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "log/faceres_ms/config.py", line 19, in <module>
    train_dataset_path = os.environ["DATABASES"] + "/FaceDatabasesPublic/MsCeleb/msceleb5m_mtcnncaffe_aligned"
  File "/home/launchx/anaconda2/envs/rllab3/lib/python3.5/os.py", line 725, in __getitem__
    raise KeyError(key) from None
KeyError: 'DATABASES'

**Comment by seasonSH** [comment]
That's a bug. You can just comment that line (as well as the next line which uses the same environment variable). It is not needed in any cases. I will update the configurations in the models to avoid this problem.

Thank you

**Comment by ytgcljj** [comment]
I annotate the DATABASES two rows in the config file.
The following error occurred in operation


major: 5 minor: 2 memoryClockRate (GHz) 1.076
pciBusID 0000:01:00.0
Total memory: 11.92GiB
Free memory: 11.63GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:906] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:916] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX TITAN X, pci bus id: 0000:01:00.0)
Metagraph file: log/faceres_ms/graph.meta
Checkpoint file: log/faceres_ms/ckpt-320000
Traceback (most recent call last):apsed time: 00:00:00 	
  File "src/extract_features.py", line 86, in <module>
    main(args)
  File "src/extract_features.py", line 67, in main
    embeddings = network.extract_feature(images, args.batch_size, verbose=True)
  File "/home/launchx/DocFace/src/basenet.py", line 232, in extract_feature
    result[start_idx:end_idx] = self.sess.run(self.outputs, feed_dict=feed_dict)
  File "/home/launchx/anaconda2/envs/rllab3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/home/launchx/anaconda2/envs/rllab3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 944, in _run
    % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (1, 250, 250, 3) for Tensor 'inputs:0', which has shape '(?, 112, 96, 3)'

**Comment by seasonSH** [comment]
As mentioned in the README, all the images must be aligned using MTCNN to 112x96 to use this model. To align the images, you can check here: https://github.com/wy1iu/sphereface and https://github.com/wy1iu/sphereface/tree/master/preprocess/code

**Comment by ytgcljj** [comment]
I would like to ask, can you give me an example of your training, I first see how the effect, if I want to do the same is not necessary to install their own sphere face?

**Comment by seasonSH** [comment]
The problem is that the code of alignment uses Matlab and Caffe, so I don't put it into the repo. I can give you a demo Matlab code for aligning images using MTCNN (you need to install Caffe) if you want.

**Comment by ytgcljj** [comment]
Thank you. Please show me a Matlab code.

**Comment by seasonSH** [comment]
I have added the alignment code into the repo. Please check the updated README on how to use it.

**Comment by ytgcljj** [comment]
It's best to make a docker, so you don't want to install the environment, you can use docker.

**Comment by seasonSH** [comment]
Thank you for your suggestion.  I will check it.
