### ISSUE TITLE
import tflib error!

### ISSUE THREAD

**Issue by smartadpole** [seasonSH/DocFace#6]

**Comment by seasonSH** [comment]
Could you give more details about your error?

**Comment by Lin427** [comment]
If you use pycharm, you can solve the problem by doing the following: Right click on the src file -> Mark Directory as->Sources Root.

**Comment by smartadpole** [comment]
> If you use pycharm, you can solve the problem by doing the following: Right click on the src file -> Mark Directory as->Sources Root.

谢谢，后来解决了，之前是因为没有安装 tflib，pip install tflib 就好了 @seasonSH

**Comment by seasonSH** [comment]
> > If you use pycharm, you can solve the problem by doing the following: Right click on the src file -> Mark Directory as->Sources Root.
> 
> 谢谢，后来解决了，之前是因为没有安装 tflib，pip install tflib 就好了 @seasonSH

tflib is  not an external library. It refers to the file "src/tflib.py". Make sure you are in the correct working directory when you run the code.

**Comment by smartadpole** [comment]
> > > If you use pycharm, you can solve the problem by doing the following: Right click on the src file -> Mark Directory as->Sources Root.
> > 
> > 
> > 谢谢，后来解决了，之前是因为没有安装 tflib，pip install tflib 就好了 @seasonSH
> 
> tflib is not an external library. It refers to the file "src/tflib.py". Make sure you are in the correct working directory when you run the code.

两者都能工作，你做过 tflib 的打包和发布

**Comment by seasonSH** [comment]
That's weird... I never did. Are you sure it works?

**Comment by smartadpole** [comment]
> That's weird... I never did. Are you sure it works?

代码不报错，而且函数也都能跳转到正确的位置；整个工程并没有运行

**Comment by seasonSH** [comment]
So it's not working?

**Comment by smartadpole** [comment]
> So it's not working?

It do not work. But I'm not exactly sure whether my setting is  error.
我分别实现了numpy 和 mxnet 版本，可以工作；思路没错

**Comment by seasonSH** [comment]
I am pretty sure there is something wrong with tflib. If you still want to use this tensorflow implementation, try to uninstall tflib library you have and fix the working path.
