### ISSUE TITLE
how can I get the Public IvS dataset?

### ISSUE THREAD

**Issue by JasonJJL** [seasonSH/DocFace#7]
hello, the paper mentioned the Public IvS dataset and some other paper used the dataset for training; so I want to ask where can I get the Public IvS dataset?

**Comment by seasonSH** [comment]
Please contact the author of the follow paper for the Public IvS dataset:

Zhu, Xiangyu, et al. "Large-scale Bisample Learning on ID vs. Spot Face Recognition." arXiv preprint arXiv:1806.03018 (2018).

**Comment by HaoLiuHust** [comment]
@seasonSH Have you got the dataset?
